language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.1
      env: SYMFONY_VERSION="3.4.*"

before_install:
  - if [[ $TRAVIS_PHP_VERSION  = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-text"; else PHPUNIT_FLAGS=""; fi
  - if [[ $TRAVIS_PHP_VERSION != '5.6' ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update "symfony/symfony:$SYMFONY_VERSION"; fi

install: composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run
