language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.5'
  - '5.6'
  - '7.0'

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak

before_install:
  - if [[ $TRAVIS_PHP_VERSION  = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-text"; else PHPUNIT_FLAGS=""; fi
  - if [[ $TRAVIS_PHP_VERSION != '5.6' ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - if [[ "$COMPOSER_FLAGS" != "" ]]; then composer require --dev --no-update phpunit/phpunit=4.8.26; fi;

install: composer update $COMPOSER_FLAGS --prefer-dist

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
