language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPENDENCIES=""
    - php: 7.2
      env:
        - DEPENDENCIES=""
    - php: 7.3
      env:
        - DEPENDENCIES=""
    - php: 7.3
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 7.4
      env:
        - DEPENDENCIES=""
        - CS_CHECK=true
        - ANALYSE=true
        - TEST_COVERAGE=true
    - php: 8.0
      env:
        - DEPENDENCIES=""

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update $DEPENDENCIES

script:
  - if [[ $CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs -n; fi
  - if [[ $ANALYSE == 'true' ]]; then ./vendor/bin/phpstan analyze; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then XDEBUG_MODE=coverage php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text; else ./vendor/bin/phpunit; fi
