language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist

script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: Test
      env: DEPENDENCIES=low
      install:
        - travis_retry composer update --prefer-dist --prefer-lowest

    - stage: Test
      env: COVERAGE
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - vendor/bin/phpunit --coverage-text

    - stage: Code Quality
      php: 7.3
      install:
        - travis_retry composer install --prefer-dist
      script:
        - vendor/bin/phpcs -n

    - stage: Static Code Analysis
      php: 7.3
      install:
        - travis_retry composer install --prefer-dist
      script:
        - vendor/bin/phpstan analyse
